### ISSUE TITLE
Problem with the latest version

### ISSUE THREAD

**Issue by josebenitezg** [verloop/labelit#28]
I have tried with the latest version of Label-studio and everything looks good until you want o open Labeling UI.

Can you guess what could be happening?

[2021-07-15 22:16:08,977] [label_studio.server] [ERROR] Exception on /labelit [GET]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/repos/labelit/labelit/flaskapp/server.py", line 40, in labelit_labeling_page
    project = server.project_get_or_create()
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/label_studio/server.py", line 71, in project_get_or_create
    'multi_session': True,
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/label_studio/project.py", line 721, in get_or_create
    project = cls.get(project_name, args, context)
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/label_studio/project.py", line 704, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/label_studio/project.py", line 692, in _load_from_dir
    return cls(config, project_name, context)
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/label_studio/project.py", line 59, in __init__
    self.load_converter()
  File "/home/ubuntu/anaconda3/envs/label-studio/lib/python3.7/site-packages/label_studio/project.py", line 138, in load_converter
    self.converter = Converter(self.parsed_label_config)
TypeError: __init__() missing 1 required positional argument: 'project_dir'
[2021-07-15 22:16:08,977] [werkzeug] [INFO] 127.0.0.1 - - [15/Jul/2021 22:16:08] "GET /labelit HTTP/1.1" 500 -
Normalizing response headers
Checking for invalid cookies
Internal Server Error: /label/asdf/labelit
Internal Server Error: /label/asdf/labelit

**Comment by ashmeet13** [comment]
Hi @josebenitezg,
Sorry for the late reply.

As of now `labelit` only works with the `label-studio==0.6.0` version that is locked in `requirements.txt`

On another note, from the stacktrace you have provided I see that the error is 
```
 TypeError: init() missing 1 required positional argument: 'project_dir'
```
Which is happening because the latest version of `label-studio-converter` was being used. The requirements have been updated to lock the version of this library to a version compatible with the current version of labelit.

Thanks!

**Comment by bilykigor** [comment]
have same issue with label-studio==0.6.0
fixed when used label-studio-converter==0.0.17
